language: python
python:
        - "2.6"
        - "2.7"
        - "3.2"
        - "3.3"
install:
        - pip install pylint
        - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then 2to3 -w pyopenkeyval.py; fi
script:
        - pylint -E pyopenkeyval.py
 
